modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="ganjacraft"
version="0.5 sativa cannapdate"
displayName="GanjaCraft"
credits="contribute on github"
displayURL="https://github.com/warlon-mhite/ganjacraft"
logoFile="logo.png"
authors="Warlon Mhite"
description='''
The most ambicious stoner mod in MineCraft history
'''

[[dependencies.ganjacraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




