modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="ganjatech"
version="0.0.1"
displayName="GanjaTech"
displayURL="https://github.com/warlon-mhite/ganjacraft"
logoFile="logo.png"
credits="join the cannadiscord | contribute on github"
authors="PopPunkNerd"
description="Weed growing and processing mod"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ganjatech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration