modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="ganjacraft"
version="0.4"
displayName="GanjaCraft"
credits="mod by Warlon mhite"
displayURL="https://github.com/warlon-mhite/ganjacraft"
logoFile="logo.png"
authors="Warlon Mhite"
description='''
Add useful and funny weed related content to the game
'''

[[dependencies.ganjacraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




